import {PDFDocument,StandardFonts,rgb} from './vendor/pdf-lib.js';
import {createExercise} from './bank.js';import {progress} from './session.js';
const safe=text=>String(text??'').replace(/\t/g,'    ').replace(/[^\x20-\x7e\xa0-\xff\n]/g,c=>({'€':'EUR','–':'-','—':'-','‘':"'",'’':"'",'“':'"','”':'"','…':'...','→':'->','✓':'OK','×':'x'}[c]??`[U+${c.codePointAt(0).toString(16).toUpperCase()}]`));
export async function makeReport(session,name=''){const doc=await PDFDocument.create();doc.setTitle('Aula Unix · Informe de práctica');doc.setAuthor('Aula Unix');doc.setSubject('Enunciados, intentos, salida de consola y soluciones de referencia');const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),mono=await doc.embedFont(StandardFonts.Courier);const ink=rgb(.10,.17,.15),green=rgb(.09,.30,.24),muted=rgb(.35,.41,.39);let page,y;
 function newPage(){page=doc.addPage([595.28,841.89]);page.drawRectangle({x:0,y:797,width:595.28,height:45,color:green});page.drawText('AULA UNIX / INFORME DE PRACTICA',{x:42,y:814,size:10,font:bold,color:rgb(1,1,1)});y=773;}
 function text(value,{font=regular,size=10,color=ink,space=7}={}){const width=511;for(const paragraph of safe(value).split('\n')){let line='';const tokens=paragraph.split(/(?<=\s)/);const wrapped=[];for(let token of tokens){if(font.widthOfTextAtSize(line+token,size)<=width)line+=token;else{if(line)wrapped.push(line.trimEnd());line='';while(font.widthOfTextAtSize(token,size)>width){let fit=1;while(fit<token.length&&font.widthOfTextAtSize(token.slice(0,fit+1),size)<=width)fit++;wrapped.push(token.slice(0,fit));token=token.slice(fit);}line=token;}}wrapped.push(line.trimEnd());for(const l of wrapped){if(y<55)newPage();if(l)page.drawText(l,{x:42,y,size,font,color});y-=size*1.4;}}y-=space;}
 newPage();text('Tu recorrido, documentado',{font:bold,size:23,color:green});text('Nombre: '+(name.trim()||'Sin nombre'),{font:bold,size:12});const p=session?progress(session):{correct:0,answered:0,assisted:0,total:0};text(`Modo: ${session?.mode==='exam'?'Examen':session?.mode==='themes'?'Práctica por temas':session?'Práctica por conocimientos':'Sin sesión'} | Preguntas: ${p.total}\nContestadas: ${p.answered} | Objetivos conseguidos: ${p.correct} | Con ayuda: ${p.assisted}\nInicio: ${session?.started??'-'}\nExportación: ${new Date().toISOString()}`);text('Este informe documenta aprendizaje en una consola Unix simulada. El reloj, los procesos, los paquetes y el disco son virtuales. Las ayudas se registran también en modo examen. No constituye una certificación ni una evaluación protegida contra consulta.',{color:muted});
 for(const [index,id] of (session?.route??[]).entries()){const ex=createExercise(id),item=session.items[id];if(y<660)newPage();else y-=12;text(`${index+1}. ${ex.title}`,{font:bold,size:16,color:green});text(`ID: ${id} | Tema ${ex.theme} | Nivel ${ex.stage+1}\nFuente adaptada: ${ex.displaySource}`,{size:9,color:muted});text(ex.task,{font:bold});text(`Estado: ${item?.correct?'Objetivo conseguido':item?.records?.length?'Contestada, objetivo pendiente':'Sin contestar'} | Comprobaciones: ${item?.attempts??0} | Pistas consultadas: ${item?.hints??0} | Resolución consultada: ${item?.revealed?'Sí':'No'}`,{size:9});
 text('Transcripción del alumno',{font:bold,size:11});if(!item?.records.length)text('No se ejecutaron órdenes en esta pregunta.',{color:muted});for(const r of item?.records??[]){text('$ '+r.cmd,{font:mono,size:9,color:green,space:2});if(r.input)text('[Entrada estándar]\n'+r.input,{font:mono,size:8,space:2});text('[stdout]\n'+(r.out||'(vacía)'),{font:mono,size:8,space:2});if(r.err)text('[stderr]\n'+r.err,{font:mono,size:8,space:2});text('Código de salida: '+r.code,{size:8,color:muted,space:4});}
 text('Resolución de referencia y salida',{font:bold,size:11});for(const r of ex.canonical){text('$ '+r.cmd,{font:mono,size:9,color:green,space:2});text('[stdout]\n'+(r.out||'(vacía: comprueba el cambio de estado)'),{font:mono,size:8,space:2});if(r.err)text('[stderr]\n'+r.err,{font:mono,size:8,space:2});text(r.info,{size:9,color:muted});}if(ex.solutions.length>1){text('Otras soluciones aceptadas',{font:bold,size:10});for(const solution of ex.solutions.slice(1))text(solution.join('\n'),{font:mono,size:8});}text('Se evalúa el resultado o el estado solicitado, no la coincidencia literal con una orden. Otras soluciones compatibles pueden ser válidas.',{size:9,color:muted});
 const changed=Object.keys(ex.expected.fs).filter(path=>{const a=ex.initial.nodes[ex.initial.fs[path]],b=ex.expected.nodes[ex.expected.fs[path]];return !a||a.content!==b.content||a.mode!==b.mode;});if(changed.length){text('Estado esperado tras resolver',{font:bold,size:10});for(const path of changed){const n=ex.expected.nodes[ex.expected.fs[path]];text(`${path} | ${n.type} | modo ${n.mode.toString(8)}`+(n.content?'\n'+n.content:''),{font:mono,size:8});}}
 }
 const pages=doc.getPages();pages.forEach((p,i)=>{p.drawLine({start:{x:42,y:38},end:{x:553,y:38},thickness:.5,color:rgb(.8,.84,.81)});p.drawText(`Aula Unix - ${safe(name.trim()||'Sin nombre').slice(0,40)} / ${i+1} de ${pages.length}`,{x:42,y:24,size:8,font:regular,color:muted});});return doc.save();}
