import {chooseRoute,createExercise,TEMPLATES,VARIANTS} from './bank.js';
export const STORAGE_KEY='aulaUnix.v1';
export function freshState(){return {version:1,name:'',seen:[],session:null,archives:[],largeText:false};}
export function validState(data){const validSession=s=>s&&Array.isArray(s.route)&&s.route.length>0&&s.route.every(id=>{if(typeof id!=='string')return false;const [key,v,...rest]=id.split(':');return !rest.length&&/^\d+$/.test(v??'')&&Number(v)<VARIANTS&&TEMPLATES.some(t=>t.id===key);})&&Number.isInteger(s.index)&&s.index>=0&&s.index<s.route.length&&s.items&&typeof s.items==='object'&&Object.values(s.items).every(i=>i&&Array.isArray(i.records)&&i.shell?.fs&&i.shell?.nodes&&i.shell?.env&&typeof i.shell.cwd==='string'&&Array.isArray(i.shell.history));return data?.version===1&&typeof data.name==='string'&&Array.isArray(data.seen)&&Array.isArray(data.archives)&&data.archives.every(validSession)&&(!data.session||validSession(data.session));}
export function loadState(storage){try{const value=JSON.parse(storage.getItem(STORAGE_KEY));return validState(value)?value:freshState();}catch{return freshState();}}
export function saveState(storage,state){try{storage.setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch{return false;}}
export function newSession(state,mode,selections,random=Math.random){const route=chooseRoute(mode,selections,state.seen,random);if(state.session){state.archives.unshift(state.session);state.archives=state.archives.slice(0,3);}state.seen=[...new Set([...state.seen,...route])];state.session={id:globalThis.crypto?.randomUUID?.()??String(Date.now()),mode,selections,route,index:0,items:{},started:new Date().toISOString(),finished:null};return state.session;}
export function currentItem(session){const id=session.route[session.index];if(!session.items[id]){const ex=createExercise(id);session.items[id]={shell:structuredClone(ex.initial),records:[],hints:0,revealed:false,correct:false,attempts:0,clearAt:0,input:''};}return session.items[id];}
export function progress(session){const items=Object.values(session.items);return {correct:items.filter(i=>i.correct).length,answered:items.filter(i=>i.records.some(r=>r.cmd!=='[Restablecer entorno]')).length,assisted:items.filter(i=>i.hints||i.revealed).length,total:session.route.length};}
