/* Entorno Unix didáctico. Nunca ejecuta código del equipo anfitrión. */
export const HOME='/home/alumno';
const encoder=new TextEncoder();
export const bytes=s=>encoder.encode(s).length;
export const lines=s=>s? s.replace(/\n$/,'').split('\n'):[];
const ok=(out='',info='')=>({out,err:'',code:0,info});
const fail=(err,code=1)=>({out:'',err:err+'\n',code,info:'La orden no se ha completado. Lee el mensaje de error y comprueba la ruta y las opciones.'});
export function pathOf(s,path='.') {let value=path.startsWith('~')?HOME+path.slice(1):path;const parts=(value.startsWith('/')?value:s.cwd+'/'+value).split('/');const stack=[];for(const p of parts){if(!p||p==='.')continue;if(p==='..')stack.pop();else stack.push(p);}return '/'+stack.join('/');}
const parent=p=>p.slice(0,p.lastIndexOf('/'))||'/';
export function node(s,p,follow=true,depth=0){p=pathOf(s,p);const id=s.fs[p];const n=s.nodes[id];if(n?.type==='link'&&follow){if(depth>12)throw Error('Demasiados enlaces simbólicos');return node(s,pathOf({...s,cwd:parent(p)},n.target),true,depth+1);}return n;}
export function add(s,p,type='file',content='',mode){p=pathOf(s,p);if(p!=='/'&&!s.fs[parent(p)])add(s,parent(p),'dir');const id=++s.next;const n={type,content,mode:mode??((type==='dir'?0o777:0o666)&~s.mask),uid:p.startsWith(HOME)?1000:0,gid:1000,mtime:s.now};s.fs[p]=id;s.nodes[id]=n;return n;}
export function hasAccess(s,p,bit){const n=node(s,p);if(!n)return false;const shift=n.uid===1000?6:n.gid===1000?3:0;return ((n.mode>>shift)&bit)===bit;}
function traverse(s,p){const parts=pathOf(s,p).split('/').filter(Boolean);let q='/';for(const x of parts.slice(0,-1)){q=(q==='/'?'':q)+'/'+x;if(!hasAccess(s,q,1))throw Error(q+': permiso de búsqueda/ejecución denegado');}}
export function read(s,p){p=pathOf(s,p);traverse(s,p);const n=node(s,p);if(!n)throw Error(p+': no existe');if(n.type==='dir')throw Error(p+': es un directorio');if(!hasAccess(s,p,4))throw Error(p+': permiso de lectura denegado');return n.content;}
export function write(s,p,text,append=false){p=pathOf(s,p);traverse(s,p);if(p==='/dev/null')return;let n=node(s,p);if(n){if(n.type==='dir')throw Error(p+': es un directorio');if(!hasAccess(s,p,2))throw Error(p+': permiso de escritura denegado');}else{if(!node(s,parent(p)))throw Error(parent(p)+': no existe');if(!hasAccess(s,parent(p),3))throw Error(parent(p)+': el directorio necesita escritura y búsqueda');n=add(s,p);}n.content=(append?n.content:'')+text;n.mtime=s.now;}
export function list(s,p='.',all=false){p=pathOf(s,p);traverse(s,p);if(!node(s,p)||node(s,p).type!=='dir')throw Error(p+': no es un directorio');if(!hasAccess(s,p,4))throw Error(p+': permiso de lectura denegado');return Object.keys(s.fs).filter(q=>q!==p&&parent(q)===p&&(all||!q.split('/').at(-1).startsWith('.'))).sort();}
export function modeText(n){return (n.type==='dir'?'d':n.type==='link'?'l':'-')+Array.from({length:9},(_,i)=>(n.mode&(1<<(8-i)))?'rwx'[i%3]:'-').join('');}
function links(s,p){const id=s.fs[pathOf(s,p)];return Object.values(s.fs).filter(x=>x===id).length;}
export function makeShell(seed=0){const s={cwd:HOME,env:{USER:'alumno',UID:'1000',HOME,SHELL:'/bin/bash',PATH:'/usr/bin:/bin',HOSTNAME:'aula-unix',LANG:'C.UTF-8'},aliases:{},mask:0o022,fs:{},nodes:{},next:0,now:1791100800000+seed*60000,history:[],processes:[{user:'root',pid:1,ppid:0,cmd:'systemd'},{user:'root',pid:55,ppid:1,cmd:'sshd'},{user:'alumno',pid:100,ppid:55,cmd:'bash'},{user:'alumno',pid:120,ppid:100,cmd:'sleep 30'},{user:'ana',pid:130,ppid:55,cmd:'python3'},{user:'alumno',pid:140,ppid:100,cmd:'editor'},{user:'bea',pid:160,ppid:55,cmd:'bash'}],packages:{},catalog:{mixxx:'Mezclador de música',biotools:'Herramientas de bioinformática',bioseq:'Análisis de secuencias',bioalign:'Alineación biológica',htop:'Monitor de procesos',tree:'Árbol de directorios'},updated:false,upgraded:false};
 for(const p of ['/','/home',HOME,'/usr','/usr/bin','/bin','/etc','/tmp','/dev','/var','/var/log'])add(s,p,'dir','',p.startsWith(HOME)?0o755:p==='/tmp'?0o777:0o755);
 add(s,'/dev/null','file','',0o666);add(s,'/etc/passwd','file','root:x:0:0:root:/root:/bin/bash\nsshd:x:50:50:SSH:/var/empty:/usr/sbin/nologin\nalumno:x:1000:1000:Estudiante:/home/alumno:/bin/bash\nana:x:1001:1001:Ana:/home/ana:/bin/bash\nbea:x:1002:1002:Bea:/home/bea:/bin/bash\n',0o644);
 add(s,'/etc/services','file','ssh 22/tcp\nhttp 80/tcp\nhttps 443/tcp\n',0o644);add(s,HOME+'/.bashrc','file','export CURSO=unix\nalias ll="ls -l"\n');add(s,HOME+'/.bash_login','file','echo Bienvenido\n');
 for(const name of ['echo','env','exit','ECHO','editor','edit','eject','awk','od','uname','id','head','grep','sort','tail'])add(s,'/usr/bin/'+name,'file','',0o755);
 return s;
}
export const globRE=pattern=>new RegExp('^'+pattern.replace(/[.+^${}()|\\]/g,'\\$&').replace(/\*/g,'[^/]*').replace(/\?/g,'[^/]').replace(/\[!/g,'[^')+'$');
function lex(text){const out=[];let raw='',q='',escaped=false,sub=0,back=false;const flush=()=>{if(raw){out.push({raw});raw='';}};for(let i=0;i<text.length;i++){const c=text[i];if(escaped){raw+=c;escaped=false;continue;}if(c==='\\'&&q!=="'"){raw+=c;escaped=true;continue;}if(back){raw+=c;if(c==='`')back=false;continue;}if(c==='`'&&q!=="'"){raw+=c;back=true;continue;}if(sub){raw+=c;if(c==='(')sub++;if(c===')')sub--;continue;}if(c==='$'&&text[i+1]==='('&&q!=="'"){raw+='$(';i++;sub=1;continue;}if(q){raw+=c;if(c===q)q='';continue;}if(c==='"'||c==="'"){q=c;raw+=c;continue;}if(c==='#'&&!raw){while(i<text.length&&text[i]!=='\n')i++;if(i<text.length){flush();out.push(';');}continue;}if(/\s/.test(c)){flush();if(c==='\n')out.push(';');continue;}if('|;&()<>'.includes(c)){if((c==='>'||c==='<')&&raw==='2'){raw='';out.push('2'+c+(text[i+1]===c?(i++,c):''));continue;}flush();let op=c;if(text[i+1]===c&&'|&>'.includes(c)){op+=c;i++;}out.push(op);continue;}raw+=c;}if(q||sub||back||escaped)throw Error('Comillas, sustitución o barra invertida sin cerrar');flush();return out;}
function parse(tokens){let i=0;const sequence=()=>{const nodes=[];while(i<tokens.length&&tokens[i]!==')'){if(tokens[i]===';'){i++;continue;}const stages=[part()];while(tokens[i]==='|'){i++;stages.push(part());}const after=[';','&&','||'].includes(tokens[i])?tokens[i++]:null;nodes.push({stages,after});if(!after&&i<tokens.length&&tokens[i]!==')')throw Error('Operador no compatible: '+String(tokens[i]));}return nodes;};const part=()=>{let group=null,words=[],redirs=[];if(tokens[i]==='('){i++;group=sequence();if(tokens[i++]!==')')throw Error('Falta cerrar el grupo con )');}while(i<tokens.length&&![';','&&','||','|',')'].includes(tokens[i])){const t=tokens[i++];if(['>','>>','<','2>','2>>'].includes(t)){const target=tokens[i++];if(!target?.raw)throw Error('La redirección necesita un archivo');redirs.push({op:t,target});}else{if(!t?.raw)throw Error('Operador no compatible: '+t);words.push(t);}}if(!group&&!words.length)throw Error('Falta una orden');return {group,words,redirs};};const tree=sequence();if(i<tokens.length)throw Error('Paréntesis inesperado');return tree;}
function child(s){return {...structuredClone(s),fs:s.fs,nodes:s.nodes,processes:s.processes};}
function expand(s,token,depth){let text='',q='',quoted=false;const raw=token.raw;for(let i=0;i<raw.length;i++){let c=raw[i];if(c==='\\'&&q!=="'"){const next=raw[++i];if(q==='"'&&!['$','`','"','\\','\n'].includes(next))text+='\\';text+=next??'';quoted=true;continue;}if(c===q){q='';quoted=true;continue;}if((c==='"'||c==="'")&&!q){q=c;quoted=true;continue;}if(q!=="'"&&c==='`'){const end=raw.indexOf('`',i+1);const subState=child(s),sub=run(subState,raw.slice(i+1,end),{depth:depth+1,record:false});s.next=Math.max(s.next,subState.next);if(sub.code)throw Error(sub.err.trim());text+=sub.out.replace(/\n+$/,'');i=end;continue;}if(q!=="'"&&c==='$'&&raw[i+1]==='('){let j=i+2,n=1,sq='';for(;j<raw.length;j++){if(sq){if(raw[j]===sq)sq='';continue;}if(raw[j]==="'"||raw[j]==='"'){sq=raw[j];continue;}if(raw[j]==='(')n++;if(raw[j]===')'&&--n===0)break;}const subState=child(s),sub=run(subState,raw.slice(i+2,j),{depth:depth+1,record:false});s.next=Math.max(s.next,subState.next);if(sub.code)throw Error(sub.err.trim());text+=sub.out.replace(/\n+$/,'');i=j;continue;}if(q!=="'"&&c==='$'){const m=raw.slice(i+1).match(/^(?:\{([A-Za-z_]\w*)\}|([A-Za-z_]\w*|\?))/);if(m){const key=m[1]||m[2];text+=key==='?'?String(s.lastCode??0):(s.env[key]??'');i+=m[0].length;continue;}}if(i===0&&c==='~'&&!q){text+=HOME;continue;}text+=c;}const chunks=quoted?[text]:text.split(/\s+/).filter(Boolean);return chunks.flatMap(v=>{if(!quoted&&/[\[*?]/.test(v)){const absolute=pathOf(s,v);const re=globRE(absolute);const hits=Object.keys(s.fs).filter(p=>re.test(p)&&!p.split('/').some((seg,j)=>seg.startsWith('.')&&!absolute.split('/')[j]?.startsWith('.'))).sort();if(hits.length)return hits.map(p=>v.startsWith('/')?p:p.slice(s.cwd.length+1));}return [v];});}
function executePart(s,p,input,depth){let result;const args=p.words.flatMap(w=>expand(s,w,depth));const redirects=p.redirs.map(r=>({...r,path:expand(s,r.target,depth)}));for(const r of redirects){if(r.path.length!==1)throw Error('Redirección ambigua');if(r.op==='<')input=read(s,r.path[0]);else if(!r.op.startsWith('2'))write(s,r.path[0],'',r.op==='>>');}
 if(p.group){const sub=child(s);result=executeTree(sub,p.group,input,depth+1);s.next=Math.max(s.next,sub.next);}else result=command(s,args,input,depth);
 for(const r of redirects){if(r.op==='>'||r.op==='>>'){write(s,r.path[0],result.out,true);result.out='';}if(r.op==='2>'||r.op==='2>>'){write(s,r.path[0],result.err,r.op==='2>>');result.err='';}}return result;
}
function executeTree(s,tree,input='',depth=0){let out='',err='',code=0,info='',previous=null,flags={};for(const chain of tree){if(previous==='&&'&&code!==0||previous==='||'&&code===0){previous=chain.after;continue;}let piped=input;for(let i=0;i<chain.stages.length;i++){const target=chain.stages.length>1?child(s):s;let r;try{r=executePart(target,chain.stages[i],piped,depth);}catch(e){r=fail(e.message);}s.next=Math.max(s.next,target.next);piped=r.out;err+=r.err;code=r.code;info=r.info;flags={clear:!!r.clear,needsInput:!!r.needsInput};}out+=piped;previous=chain.after;}s.lastCode=code;return {out,err,code,info,...flags};}
export function run(s,text,{depth=0,record=true,input=''}={}){if(depth>10)return fail('Límite de anidación alcanzado');if(typeof text!=='string'||text.length>4000)return fail('La orden puede tener como máximo 4000 caracteres');if(record&&text.trim())s.history.push(text);try{const r=executeTree(s,parse(lex(text)),input,depth);if(bytes(r.out)+bytes(r.err)>60000)return {...fail('La salida supera el límite didáctico de 60 kB'),out:r.out.slice(0,30000)};return r;}catch(e){return fail(e.message);}}
function inputs(s,args,stdin){return args.length?args.map(p=>read(s,p)).join(''):stdin;}
function option(args,name){let i=args.indexOf(name);if(i>=0)return args[i+1];const x=args.find(a=>a.startsWith(name)&&a.length>name.length);return x?.slice(name.length);}
function regex(pattern,extended=false,ignore=false){if(pattern.length>160)throw Error('Expresión demasiado larga (máximo 160 caracteres)');if(/\\[1-9]|\(\?|(?:\*|\+|\})[+*{]|\([^)]*[+*][^)]*\)[+*{]/.test(pattern))throw Error('Esta expresión no está soportada por el motor didáctico. Usa una expresión POSIX sencilla.');pattern=pattern.replace(/\[:(digit|alpha|alnum|lower|upper|space|blank|xdigit):\]/g,(_,name)=>({digit:'0-9',alpha:'A-Za-z',alnum:'A-Za-z0-9',lower:'a-z',upper:'A-Z',space:'\\s',blank:' \\t',xdigit:'A-Fa-f0-9'}[name]));let converted='',bracket=false;for(let i=0;i<pattern.length;i++){const c=pattern[i];if(c==='\\'){const n=pattern[++i];if(n===undefined)throw Error('Barra invertida sin cerrar');if(n==='<'||n==='>')converted+='\\b';else if(!extended&&'+?|(){}'.includes(n)&&!bracket)converted+=n;else converted+='\\'+n;}else{if(c==='[')bracket=true;if(c===']')bracket=false;converted+=!extended&&!bracket&&'+?|(){}'.includes(c)?'\\'+c:c;}}return new RegExp(converted,ignore?'i':'');}
function command(s,args,stdin,depth){let cmd=args.shift();if(!cmd)return ok();if(/^[A-Za-z_]\w*=/.test(cmd)){const [key,...v]=cmd.split('=');if(key==='UID')return fail('UID: variable de solo lectura');if(args.length){const local={...s,env:{...s.env,[key]:v.join('=')}};return command(local,args,stdin,depth);}s.env[key]=v.join('=');return ok('','Has definido una variable del entorno de práctica.');}if(s.aliases[cmd])return run(s,s.aliases[cmd]+(args.length?' '+args.map(a=>"'"+a.replace(/'/g,"'\\''")+"'").join(' '):''),{depth:depth+1,record:false,input:stdin});
 if(cmd==='sudo'){if(!['apt','apt-get','apt-cache'].includes(args[0]))return fail('sudo: solo se simula para la gestión de paquetes del temario');return command(s,args,stdin,depth);}
 if(cmd==='help'||cmd==='man'){return ok('Órdenes disponibles: '+COMMANDS.join(', ')+'.\nConsulta el diccionario de la aplicación para opciones y ejemplos.\n','La ayuda describe el subconjunto implementado. No se ejecutan órdenes de tu equipo.');}

 const flagRules={pwd:/^$/,ls:/^-[1lAaFdq]+$/,mkdir:/^-p$/,touch:/^$/,cat:/^-n$/,less:/^$/,more:/^$/,tee:/^-a$/,wc:/^-[lwcm]+$/,chmod:/^$/,umask:/^$/,cp:/^$/,mv:/^$/,rm:/^-[rf]+$/,rmdir:/^$/,ln:/^-s$/,id:/^-[ug]$/,whoami:/^$/,who:/^$/,ps:/^-(?:e|f|ef|fe)$/,kill:/^-(?:TERM|KILL|15|9)$/,uname:/^-[anm]$/,date:/^$/,sleep:/^$/,whereis:/^$/,od:/^-c$/,env:/^$/,du:/^-(?:b|h)$/,df:/^-h$/};
 if(flagRules[cmd]){const bad=args.find(a=>a.startsWith('-')&&a!=='-'&&!flagRules[cmd].test(a));if(bad)return fail(cmd+': opción no implementada '+bad+'. Consulta el diccionario.');}
 if(cmd==='pwd')return ok(s.cwd+'\n','Esta es la ruta absoluta del directorio de trabajo. / es la raíz; cada / separa un nivel.');
 if(cmd==='cd'){const p=pathOf(s,args[0]??HOME);traverse(s,p+'/x');if(!node(s,p)||node(s,p).type!=='dir')return fail('cd: '+p+': no es un directorio');if(!hasAccess(s,p,1))return fail('cd: permiso de búsqueda/ejecución denegado');s.cwd=p;s.env.PWD=p;return ok('','cd no imprime nada cuando tiene éxito. Usa pwd para comprobar la ubicación.');}
 if(cmd==='ls'){const flags=args.filter(a=>a.startsWith('-')).join('');const paths=args.filter(a=>!a.startsWith('-'));let output=[];for(const p of paths.length?paths:['.']){const absolute=pathOf(s,p),n=node(s,p,false);if(!n)return fail('ls: '+p+': no existe');let children=n.type==='dir'&&!flags.includes('d')?list(s,p,flags.includes('a')||flags.includes('A')):[absolute];if(n.type==='dir'&&flags.includes('a'))children=[absolute+'/.',absolute+'/..',...children];for(const q of children){const f=node(s,q,false),name=paths.length&&n.type!=='dir'?p:q.split('/').at(-1);const label=name+(flags.includes('F')?(f.type==='dir'?'/':f.type==='link'?'@':f.mode&0o111?'*':''):'');output.push(flags.includes('l')?`${modeText(f)} ${links(s,q)} ${f.uid===1000?'alumno':'root'} alumnos ${bytes(f.content??'')} Oct 04 12:00 ${label}${f.type==='link'?' -> '+f.target:''}`:label);}}return ok(output.join('\n')+(output.length?'\n':''),'Cada fila es una entrada. En ls -l: tipo y permisos, enlaces, propietario, grupo, bytes, fecha y nombre. Esta consola muestra una entrada por línea.');}
 if(cmd==='mkdir'){const recursive=args.includes('-p');for(const p of args.filter(a=>!a.startsWith('-'))){const q=pathOf(s,p);if(node(s,q)){if(recursive&&node(s,q).type==='dir')continue;return fail('mkdir: '+p+': ya existe');}if(recursive){let at='/';for(const bit of q.split('/').filter(Boolean)){at=(at==='/'?'':at)+'/'+bit;if(!node(s,at)){if(!hasAccess(s,parent(at),3))return fail('mkdir: permiso denegado');add(s,at,'dir');}else if(node(s,at).type!=='dir')return fail('mkdir: no es un directorio');}}else{if(!node(s,parent(q)))return fail('mkdir: falta el directorio padre (usa -p)');if(!hasAccess(s,parent(q),3))return fail('mkdir: permiso denegado');add(s,q,'dir');}}return ok('','Los directorios se han creado. La ausencia de salida es normal. Comprueba con ls.');}
 if(cmd==='touch'){if(!args.length)return fail('touch: falta un nombre');for(const p of args){if(node(s,p)){node(s,p).mtime=s.now;}else write(s,p,'');}return ok('','touch crea un archivo vacío o actualiza su fecha de modificación.');}
 if(cmd==='cat'||cmd==='less'||cmd==='more'){const paths=args.filter(a=>!a.startsWith('-'));if(!paths.length&&!stdin)return {out:'',err:'',code:0,info:'La orden espera entrada estándar. Usa el campo «Entrada estándar» para escribir texto y finalizarlo en esta consola.',needsInput:true};let out=inputs(s,paths,stdin);if(cmd==='cat'&&args.includes('-n'))out=lines(out).map((l,i)=>`${i+1}\t${l}`).join('\n')+'\n';return ok(out,cmd==='cat'?'Se muestra el contenido, no los nombres de los archivos.':'El contenido se muestra en el panel desplazable de la consola; aquí no se abre un paginador externo.');}
 if(cmd==='echo'){let newline=true,escapes=false;while(['-n','-e','-E'].includes(args[0])){const a=args.shift();if(a==='-n')newline=false;if(a==='-e')escapes=true;}let out=args.join(' ');if(escapes)out=out.replace(/\\([ntr\\])/g,(_,c)=>({n:'\n',t:'\t',r:'\r','\\':'\\'}[c]));return ok(out+(newline?'\n':''),'echo muestra sus argumentos después de expandir variables y sustituciones.');}
 if(cmd==='printf'){const fmt=args.shift()??'';let i=0;const out=fmt.replace(/\\([ntr\\])/g,(_,c)=>({n:'\n',t:'\t',r:'\r','\\':'\\'}[c])).replace(/%([sdi%])/g,(_,c)=>c==='%'?'%':c==='s'?String(args[i++]??''):String(Number(args[i++]??0)));return ok(out,'printf aplica el formato: %s texto, %d entero, \\n salto de línea y \\t tabulación.');}
 if(cmd==='tee'){const append=args.includes('-a');for(const p of args.filter(a=>!a.startsWith('-')))write(s,p,stdin,append);return {...ok(stdin,'tee copia la entrada estándar a un archivo y también a la salida estándar.'),needsInput:!stdin};}
 if(cmd==='head'||cmd==='tail'){let count=10,kind='lines',files=[];for(let i=0;i<args.length;i++){const a=args[i];if(a==='-n'||a==='-c'){kind=a==='-c'?'bytes':'lines';count=Number(args[++i]);}else if(/^-\d+$/.test(a))count=Number(a.slice(1));else if(/^-[nc][+-]?\d+$/.test(a)){kind=a[1]==='c'?'bytes':'lines';count=Number(a.slice(2));}else if(/^\+\d+$/.test(a))count=Number(a);else files.push(a);}if(!Number.isFinite(count))return fail(cmd+': número no válido');const raw=inputs(s,files,stdin);let rows=kind==='bytes'?Array.from(encoder.encode(raw)):lines(raw);const fromStart=args.some(a=>/^\+\d+$/.test(a))||args.includes('+'+count);const selected=cmd==='head'?(count<0?rows.slice(0,count):rows.slice(0,count)):(fromStart?rows.slice(count-1):count<0?rows.slice(-count):rows.slice(-count));const out=kind==='bytes'?new TextDecoder().decode(new Uint8Array(selected)):selected.join('\n')+(selected.length?'\n':'');return ok(out,`${cmd} selecciona ${kind==='bytes'?'bytes':'líneas'} ${cmd==='head'?'desde el principio':'desde el final'}. -n +N en tail empieza en la línea N.`);}
 if(cmd==='wc'){const flags=args.filter(a=>a.startsWith('-')).join('');const files=args.filter(a=>!a.startsWith('-'));const out=(files.length?files:[null]).map(p=>{const t=p?read(s,p):stdin;const counts={l:(t.match(/\n/g)||[]).length,w:(t.trim()?t.trim().split(/\s+/).length:0),c:bytes(t),m:Array.from(t).length};const selected=flags?[...flags.replace(/-/g,'')].map(k=>counts[k]):[counts.l,counts.w,counts.c];if(selected.some(n=>n===undefined))throw Error('wc: opción no soportada');return selected.join(' ')+(p?' '+p:'');});return ok(out.join('\n')+'\n','-l cuenta saltos de línea, -w palabras, -c bytes y -m caracteres. Una cabecera también cuenta como línea.');}
 if(cmd==='grep'||cmd==='egrep'||cmd==='fgrep'){let extended=cmd==='egrep',fixed=cmd==='fgrep',ignore=false,invert=false,number=false,count=false,names=false,patterns=[],files=[];for(let i=0;i<args.length;i++){let a=args[i];if(a==='-e'){patterns.push(args[++i]);continue;}if(a.startsWith('-')&&a!=='-'){for(const c of a.slice(1)){if(c==='E')extended=true;else if(c==='F')fixed=true;else if(c==='i')ignore=true;else if(c==='v')invert=true;else if(c==='n')number=true;else if(c==='c')count=true;else if(c==='l')names=true;else throw Error('grep: opción no soportada '+c);}continue;}if(!patterns.length)patterns.push(a);else files.push(a);}if(!patterns.length)throw Error('grep: falta el patrón');const expressions=patterns.map(p=>fixed?null:regex(p,extended,ignore));const out=[];let any=false;for(const file of files.length?files:[null]){const text=file?read(s,file):stdin;const found=lines(text).map((l,i)=>({l,i})).filter(({l})=>patterns.some((p,j)=>fixed?(ignore?l.toLowerCase().includes(p.toLowerCase()):l.includes(p)):expressions[j].test(l))!==invert);if(found.length)any=true;if(names){if(found.length&&file)out.push(file);}else if(count)out.push((files.length>1?file+':':'')+found.length);else for(const {l,i} of found)out.push((files.length>1?file+':':'')+(number?i+1+':':'')+l);}return {out:out.join('\n')+(out.length?'\n':''),err:'',code:any?0:1,info:any?'grep devuelve líneas completas que cumplen el patrón. -n antepone el número de línea.':'No hay coincidencias: grep devuelve código 1. Esto no es un error de sintaxis.'};}
 if(cmd==='cut'){const delimiter=option(args,'-d')??'\t';const fields=option(args,'-f');const chars=option(args,'-c');if(!fields&&!chars)return fail('cut: usa -f o -c');const used=new Set();for(let i=0;i<args.length;i++)if(['-d','-f','-c'].includes(args[i])){used.add(i);used.add(++i);}const files=args.filter((a,i)=>!used.has(i)&&!a.startsWith('-'));const select=(arr,spec)=>{const result=[];for(const range of spec.split(',')){const m=range.match(/^(\d+)?(?:-(\d+)?)?$/);if(!m||range==='')throw Error('cut: rango no válido');const start=Number(m[1]||1),end=range.includes('-')?Number(m[2]||arr.length):start;for(let i=start-1;i<Math.min(end,arr.length);i++)if(i>=0)result.push(arr[i]);}return result;};const out=lines(inputs(s,files,stdin)).map(l=>fields&&!l.includes(delimiter)?l:select(chars?Array.from(l):l.split(delimiter),chars??fields).join(chars?'':delimiter));return ok(out.join('\n')+(out.length?'\n':''),'cut selecciona campos con -f y separador -d; -c selecciona posiciones. La numeración comienza en 1.');}
 if(cmd==='sort'){let reverse=false,numeric=false,unique=false,check=false,delimiter=null,key=1,endKey=null,char=1,stable=false,files=[];for(let i=0;i<args.length;i++){const a=args[i];if(a==='-t')delimiter=args[++i];else if(a.startsWith('-t'))delimiter=a.slice(2);else if(a==='-k'||a.startsWith('-k')){const v=a==='-k'?args[++i]:a.slice(2);const bits=v.split(',')[0].split('.');key=Number(bits[0]);char=Number(bits[1]||1);endKey=v.includes(',')?Number(v.split(',')[1]):null;}else if(a.startsWith('-')){for(const c of a.slice(1)){if(c==='r')reverse=true;else if(c==='n')numeric=true;else if(c==='u')unique=true;else if(c==='c')check=true;else if(c==='s')stable=true;else throw Error('sort: opción no soportada');}}else files.push(a);}const original=lines(inputs(s,files,stdin));const value=l=>(delimiter?l.split(delimiter):l.trim().split(/\s+/)).slice(key-1,endKey??undefined).join(delimiter??' ').slice(char-1);const cmp=(a,b)=>{const x=value(a),y=value(b);let n=numeric?parseFloat(x)-parseFloat(y):x<y?-1:x>y?1:0;if(!n&&!stable&&!unique)n=a<b?-1:a>b?1:0;return reverse?-n:n;};if(check){const bad=original.findIndex((l,i)=>i&&cmp(original[i-1],l)>0);return bad<0?ok('','La lista está ordenada. sort -c no imprime salida cuando tiene éxito.'):fail('sort: desorden en la línea '+(bad+1));}let sorted=[...original].sort(cmp);if(unique)sorted=[...new Set(sorted)];return ok(sorted.join('\n')+(sorted.length?'\n':''),'sort ordena líneas. -t define el separador, -k el campo (desde 1), -r invierte y -n compara números. Se usa orden de caracteres reproducible.');}
 if(cmd==='uniq'){const count=args.includes('-c');const files=args.filter(a=>!a.startsWith('-'));const rows=lines(inputs(s,files,stdin));const grouped=[];for(const row of rows){if(grouped.at(-1)?.row===row)grouped.at(-1).count++;else grouped.push({row,count:1});}return ok(grouped.map(g=>(count?g.count+' ':'')+g.row).join('\n')+(grouped.length?'\n':''),'uniq elimina repeticiones consecutivas. Para agrupar todas, ordena antes con sort.');}
 if(cmd==='chmod'){const spec=args.shift();if(!spec||!args.length)return fail('chmod: faltan modo y archivo');for(const p of args){const n=node(s,p);if(!n)throw Error('chmod: no existe '+p);if(n.uid!==1000)throw Error('chmod: no eres el propietario');if(/^[0-7]{3,4}$/.test(spec))n.mode=parseInt(spec,8)&0o777;else for(const part of spec.split(',')){const m=part.match(/^([ugoa]*)([+=-])([rwx]*)$/);if(!m)throw Error('chmod: modo no soportado');const who=m[1]||'a';for(const [c,shift] of [['u',6],['g',3],['o',0]])if(who.includes(c)||who.includes('a')){const mask=([...(m[3])].reduce((v,x)=>v|({r:4,w:2,x:1}[x]),0))<<shift;n.mode=m[2]==='+'?n.mode|mask:m[2]==='-'?n.mode&~mask:(n.mode&~(7<<shift))|mask;}}}return ok('','Los permisos han cambiado. r=4, w=2, x=1; cada dígito octal corresponde a propietario, grupo y otros.');}
 if(cmd==='umask'){if(!args.length)return ok(s.mask.toString(8).padStart(4,'0')+'\n','La máscara quita bits: archivos parten de 666; directorios de 777. No añade ejecución a archivos.');if(!/^[0-7]{3,4}$/.test(args[0]))return fail('umask: usa formato octal');s.mask=parseInt(args[0],8)&0o777;return ok('','La máscara afecta a nuevas creaciones; no modifica los permisos de los archivos existentes.');}
 if(cmd==='cp'||cmd==='mv'){const paths=args.filter(a=>!a.startsWith('-'));if(paths.length!==2)return fail(cmd+': indica origen y destino');const [src,dest]=paths;const from=pathOf(s,src);let to=pathOf(s,dest);if(node(s,to)?.type==='dir')to+='/'+from.split('/').at(-1);if(from===to)return fail(cmd+': origen y destino son el mismo archivo');const n=node(s,from,false);if(!n)throw Error(cmd+': no existe el origen');if(n.type==='dir')throw Error(cmd+': esta consola permite copiar/mover archivos individuales');if(cmd==='cp'){const fresh=!node(s,to);write(s,to,read(s,from));if(fresh)node(s,to).mode=n.mode&~s.mask;}else{if(!hasAccess(s,parent(from),3)||!hasAccess(s,parent(to),3))throw Error('mv: permiso denegado en el directorio');s.fs[to]=s.fs[from];delete s.fs[from];}return ok('',cmd==='cp'?'cp crea una copia independiente con otro i-nodo.':'mv cambia la entrada del directorio y conserva el i-nodo.');}
 if(cmd==='rm'||cmd==='rmdir'){for(const p of args.filter(a=>!a.startsWith('-'))){const q=pathOf(s,p),n=node(s,q,false);if(!n){if(args.includes('-f'))continue;throw Error(cmd+': no existe '+p);}if(!hasAccess(s,parent(q),3))throw Error(cmd+': el directorio padre no permite escritura y búsqueda');const children=Object.keys(s.fs).filter(x=>x.startsWith(q+'/'));if(n.type==='dir'&&cmd==='rm'&&!args.some(a=>a.includes('r')))throw Error('rm: es un directorio; usa rmdir o -r');if(n.type==='dir'&&children.length&&cmd==='rmdir')throw Error('rmdir: directorio no vacío');for(const x of children)delete s.fs[x];delete s.fs[q];}return ok('','Borrar una entrada exige escritura y búsqueda en el directorio padre; no exige escritura en el archivo.');}
 if(cmd==='ln'){const symbolic=args.includes('-s');const paths=args.filter(a=>!a.startsWith('-'));if(paths.length!==2)throw Error('ln: indica origen y nombre del enlace');const [a,b]=paths;const q=pathOf(s,b);if(node(s,q,false))throw Error('ln: el destino existe');if(!hasAccess(s,parent(q),3))throw Error('ln: permiso denegado');if(symbolic){const n=add(s,q,'link','',0o777);n.target=a;}else{if(!node(s,a)||node(s,a).type!=='file')throw Error('ln: el origen debe ser un archivo existente');s.fs[q]=s.fs[pathOf(s,a)];}return ok('',symbolic?'El enlace simbólico guarda una ruta. Puede quedar roto si se borra el destino.':'El enlace duro comparte i-nodo y contenido; no crea una copia.');}
 if(cmd==='find')return find(s,args,depth);
 if(cmd==='sed')return sed(s,args,stdin);
 if(cmd==='awk')return awk(s,args,stdin);
 if(cmd==='id'){if(args.includes('-u'))return ok('1000\n','UID identifica al usuario, no al grupo.');if(args.includes('-g'))return ok('1000\n','GID identifica al grupo principal. Bash no define automáticamente $GID.');return ok('uid=1000(alumno) gid=1000(alumnos) groups=1000(alumnos)\n','uid identifica al usuario; gid, al grupo principal; groups enumera sus grupos.');}
 if(cmd==='whoami')return ok('alumno\n','Nombre del usuario efectivo del entorno.');
 if(cmd==='who')return ok('alumno pts/0 2026-10-04 12:00\nana pts/1 2026-10-04 12:05\nbea pts/2 2026-10-04 12:10\n','Cada línea es una sesión conectada, no necesariamente una persona distinta.');
 if(cmd==='ps'){const full=args.some(a=>a.includes('e')||a.includes('f'));return ok(full?'UID PID PPID C STIME TTY TIME CMD\n'+s.processes.map(p=>`${p.user} ${p.pid} ${p.ppid} 0 12:00 pts/0 00:00:00 ${p.cmd}`).join('\n')+'\n':'PID TTY TIME CMD\n'+s.processes.filter(p=>p.user==='alumno').map(p=>`${p.pid} pts/0 00:00:00 ${p.cmd}`).join('\n')+'\n','La primera línea es una cabecera. PID identifica el proceso; PPID su padre; CMD muestra la orden. Los procesos de esta consola son simulados.');}
 if(cmd==='kill'){const pid=Number(args.filter(a=>!a.startsWith('-'))[0]);const index=s.processes.findIndex(p=>p.pid===pid);if(index<0)throw Error('kill: PID inexistente');if(s.processes[index].user!=='alumno')throw Error('kill: no tienes permiso para señalar ese proceso');if(pid===100)throw Error('kill: el shell de práctica se conserva para que puedas continuar');s.processes.splice(index,1);return ok('','kill envía una señal. Aquí se simula la terminación del proceso seleccionado.');}
 if(cmd==='uname'){if(args.includes('-n'))return ok('aula-unix\n','-n muestra el nombre del equipo.');if(args.includes('-m'))return ok('x86_64\n','-m muestra la arquitectura, no el nombre del equipo.');return ok(args.includes('-a')?'Linux aula-unix 6.8.0 x86_64 GNU/Linux\n':'Linux\n','uname consulta información del sistema simulado; -a reúne varios datos.');}
 if(cmd==='date'){const d=new Date(s.now);const vals={a:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d.getUTCDay()],d:String(d.getUTCDate()).padStart(2,'0'),h:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][d.getUTCMonth()],b:null,y:String(d.getUTCFullYear()).slice(-2),Y:d.getUTCFullYear(),m:String(d.getUTCMonth()+1).padStart(2,'0'),H:String(d.getUTCHours()).padStart(2,'0'),M:String(d.getUTCMinutes()).padStart(2,'0'),S:String(d.getUTCSeconds()).padStart(2,'0'),r:'12:00:00 PM',F:d.toISOString().slice(0,10),T:d.toISOString().slice(11,19)};vals.b=vals.h;vals.r=String(d.getUTCHours()%12||12).padStart(2,'0')+':'+vals.M+':'+vals.S+' '+(d.getUTCHours()<12?'AM':'PM');return ok(args[0]?.startsWith('+')?args[0].slice(1).replace(/%([adhbyYmHMSrFT%])/g,(_,k)=>k==='%'?'%':String(vals[k]))+'\n':`${vals.a} ${vals.h} ${vals.d} ${vals.T} UTC ${vals.Y}\n`,'El reloj del ejercicio es fijo y usa UTC para que los resultados sean reproducibles. Los códigos % controlan el formato.');}
 if(cmd==='sleep'){const seconds=Number(args[0]);if(!Number.isFinite(seconds)||seconds<0||seconds>60)throw Error('sleep: usa entre 0 y 60 segundos');s.elapsed=seconds;return ok('','La espera se simula sin detener el navegador. No es una medición real del equipo.');}
 if(cmd==='time'){const r=args.length?command(s,args,stdin,depth):ok();return {...r,err:r.err+`real\t0m${Number(s.elapsed??0).toFixed(3)}s\nuser\t0m0.000s\nsys\t0m0.000s\n`,info:'time escribe las duraciones en la salida de error estándar. real es tiempo transcurrido; user y sys son tiempo de CPU. Son valores simulados.'};}
 if(cmd==='whereis')return ok(args.map(a=>a+': /usr/bin/'+a+' /usr/share/man/man1/'+a+'.1.gz').join('\n')+'\n','whereis busca binarios y páginas de manual en ubicaciones típicas del entorno simulado.');
 if(cmd==='od'){const files=args.filter(a=>!a.startsWith('-')&&!['c','x1'].includes(a));const data=encoder.encode(inputs(s,files,stdin));const character=args.includes('-c')||args.includes('c');return ok('0000000 '+[...data].map(b=>character?(b===10?'\\n':String.fromCharCode(b)):b.toString(8).padStart(3,'0')).join(' ')+'\n'+data.length.toString(8).padStart(7,'0')+'\n','od significa octal dump: muestra los bytes. -c representa caracteres; esta práctica utiliza archivos cortos.');}
 if(cmd==='export'){for(const a of args){const at=a.indexOf('=');if(at>=0)s.env[a.slice(0,at)]=a.slice(at+1);else if(!(a in s.env))s.env[a]='';}return ok('','export marca variables para el entorno; dentro de esta consola se conservan en la sesión.');}
 if(cmd==='env')return ok(Object.entries(s.env).map(([k,v])=>k+'='+v).join('\n')+'\n','Cada línea contiene una variable y su valor.');
 if(cmd==='source'||cmd==='.')return run(s,read(s,args[0]),{depth:depth+1,record:false});
 if(cmd==='exec'){if(!args.length)return ok();const r=command(s,args,stdin,depth);return {...r,info:'exec ejecuta la orden indicada. Un Bash real reemplaza el proceso del shell; aquí se conserva la interfaz para continuar aprendiendo.'};}
 if(cmd==='alias'){if(!args.length)return ok(Object.entries(s.aliases).map(([k,v])=>`alias ${k}='${v}'`).join('\n')+'\n','Un alias sustituye el nombre inicial de una orden.');for(const a of args){const at=a.indexOf('=');if(at<1)throw Error('alias: usa nombre=\'orden\'');s.aliases[a.slice(0,at)]=a.slice(at+1);}return ok('','El alias se ha definido. Invócalo en una orden posterior.');}
 if(cmd==='unalias'){for(const a of args)delete s.aliases[a];return ok();}
 if(cmd==='history'){const count=Number(args[0]||s.history.length);return ok(s.history.slice(-count).map((l,i)=>`${Math.max(1,s.history.length-count+1)+i} ${l}`).join('\n')+'\n','El historial enumera las órdenes de este ejercicio, incluida history. Flecha arriba recupera una orden anterior.');}
 if(cmd==='clear')return {...ok('','Se limpia la vista; la transcripción del informe permanece guardada.'),clear:true};
 if(cmd==='exit')return ok('La consola didáctica conserva la sesión. Usa Finalizar y Guardar para cerrar tu práctica.\n','En una terminal real, exit cierra el shell.');
 if(['apt','apt-get','apt-cache'].includes(cmd)){const action=args.shift();const pkgs=args.filter(a=>!a.startsWith('-'));if(action==='update'){s.updated=true;return ok('Índice local actualizado (simulación).\n','update actualiza la lista de paquetes; no instala nuevas versiones.');}if(action==='upgrade'){s.upgraded=true;return ok('Paquetes instalados actualizados (simulación).\n','upgrade actualiza los paquetes instalados.');}if(action==='search')return ok(Object.entries(s.catalog).filter(([k,v])=>(k+' '+v).includes(pkgs[0]??'')).map(([k,v])=>k+' - '+v).join('\n')+'\n','La búsqueda examina nombre y descripción del catálogo simulado.');if(action==='show'){const p=pkgs[0];if(!s.catalog[p])throw Error('apt: paquete no disponible');return ok(`Package: ${p}\nVersion: 1.0\nDescription: ${s.catalog[p]}\n`,'Se muestran metadatos; consultar no instala el paquete.');}if(['install','remove','purge'].includes(action)){if(!pkgs.length)throw Error('apt: falta el paquete');for(const p of pkgs){if(!s.catalog[p])throw Error('apt: paquete no disponible '+p);s.packages[p]={installed:action==='install',config:action!=='purge'&&!args.includes('--purge')};}return ok(action+' completado (simulación): '+pkgs.join(', ')+'\n','remove conserva configuración; purge la elimina. No se descarga ni modifica software real.');}throw Error('apt: acción no soportada');}
 if(s.packages[cmd]?.installed)return ok(cmd+': aplicación instalada; el arranque gráfico se representa aquí con un mensaje.\n','La instalación y el lanzamiento son simulados.');
 if(cmd==='uptime')return ok('12:00:00 up 50 min, 3 users, load average: 0.52, 0.58, 0.59\n','La carga media corresponde a 1, 5 y 15 minutos. No es el porcentaje de CPU.');
 if(cmd==='df')return ok('Filesystem Size Used Avail Use% Mounted on\n/dev/aula 20G 5G 15G 25% /\n','df muestra capacidad, uso y espacio disponible del sistema de archivos simulado.');
 if(cmd==='du'){const paths=args.filter(a=>!a.startsWith('-'));return ok((paths.length?paths:['.']).map(p=>{const q=pathOf(s,p);const size=Object.keys(s.fs).filter(x=>x===q||x.startsWith(q+'/')).reduce((n,x)=>n+bytes(node(s,x)?.content??''),0);return (args.includes('-h')?(size/1024).toFixed(1)+'K':size)+'\t'+p;}).join('\n')+'\n','du suma el contenido de este árbol virtual. -b usa bytes; -h usa unidades legibles. No estima bloques físicos.');}
 return fail(cmd+': orden no disponible. Escribe help para consultar el repertorio.',127);
}
function find(s,args,depth){let start='.';if(args[0]&&!args[0].startsWith('-')&&!['!','('].includes(args[0]))start=args.shift();const root=pathOf(s,start);if(!node(s,root,false))throw Error('find: no existe '+start);const candidates=Object.keys(s.fs).filter(p=>p===root||p.startsWith(root+'/')).sort();const outputs=[];for(const p of candidates){const n=node(s,p,false);let i=0;const actions=[];const atom=()=>{const a=args[i++];if(a==='!')return !atom();if(a==='('){const v=or();if(args[i++]!==')')throw Error('find: falta )');return v;}if(a==='-name')return globRE(args[i++]).test(p.split('/').at(-1));if(a==='-type')return n.type===({f:'file',d:'dir',l:'link'}[args[i++]]);if(a==='-empty')return n.type==='dir'?!candidates.some(q=>parent(q)===p):bytes(n.content??'')===0;if(a==='-links')return links(s,p)===Number(args[i++]);if(a==='-size'){const spec=args[i++],m=spec?.match(/^([+-]?)(\d+)([ckbMG]?)$/);if(!m)throw Error('find: tamaño no válido');const unit={c:1,k:1024,b:512,'':512,M:1048576,G:1073741824}[m[3]],size=Math.ceil(bytes(n.content??'')/unit),value=Number(m[2]);return m[1]==='+'?size>value:m[1]==='-'?size<value:size===value;}if(a==='-mtime'){const spec=args[i++],sign=spec[0],v=Number(spec.replace(/^[+-]/,'')),age=Math.floor((s.now-n.mtime)/86400000);return sign==='+'?age>v:sign==='-'?age<v:age===v;}if(a==='-newer'){const reference=node(s,args[i++]);if(!reference)throw Error('find: referencia inexistente');return n.mtime>reference.mtime;}if(a==='-perm'){const spec=args[i++],bits=parseInt(spec.replace(/^[\/-]/,''),8);if(!Number.isFinite(bits))throw Error('find: usa permisos octales');return spec[0]==='-'?(n.mode&bits)===bits:spec[0]==='/'?Boolean(n.mode&bits):n.mode===bits;}if(a==='-print'){actions.push(['print']);return true;}if(a==='-exec'){const cmd=[];while(i<args.length&&![';','+'].includes(args[i]))cmd.push(args[i++]);if(i>=args.length)throw Error('find: -exec termina en \\; o +');i++;actions.push(['exec',cmd]);return true;}if(a===undefined)return true;throw Error('find: opción no soportada '+a);};const and=()=>{let v=atom();while(i<args.length&&!['-o','-or',')'].includes(args[i])){if(['-a','-and'].includes(args[i]))i++;const rhs=atom();v=v&&rhs;}return v;};const or=()=>{let v=and();while(['-o','-or'].includes(args[i])){i++;const rhs=and();v=v||rhs;}return v;};const match=args.length?or():true;if(match){const label=start.startsWith('/')?p:start==='.'?(p===root?'.':'./'+p.slice(root.length+1)):start+(p===root?'':'/'+p.slice(root.length+1));if(!actions.length)outputs.push(label+'\n');else for(const action of actions){if(action[0]==='print')outputs.push(label+'\n');else{const cmd=action[1].map(a=>a==='{}'?label:a);const r=command(s,[...cmd],'',depth+1);if(r.code)throw Error(r.err.trim());outputs.push(r.out);}}}}return ok(outputs.join(''),'find recorre el árbol. -a combina condiciones (Y), -o ofrece alternativas (O). -size redondea hacia arriba a la unidad; -mtime 0 significa menos de 24 horas.');}
function sed(s,args,stdin){let extended=false,inplace=false,script='',files=[];for(let i=0;i<args.length;i++){if(args[i]==='-E'||args[i]==='-r')extended=true;else if(args[i]==='-i')inplace=true;else if(args[i]==='-f')script=read(s,args[++i]);else if(args[i]==='-e')script=args[++i];else if(!script)script=args[i];else files.push(args[i]);}if(!script)throw Error('sed: falta el programa');let start=1,end=Infinity;const range=script.match(/^(\d+),(\d+)\{([\s\S]*)\}$/);if(range){start=Number(range[1]);end=Number(range[2]);script=range[3];}script=script.trim();const result=[];const rows=lines(inputs(s,files,stdin));const subst=script.match(/^s(.)([\s\S]*?)\1([\s\S]*?)\1([g]*)$/);const writeDelete=script.match(/^\/(.*)\/\s*\{\s*w\s+([^\n;]+)[\n;]+\s*d\s*\}$/);const captured=[];const del=writeDelete??script.match(/^\/(.*)\/\s*(?:\{\s*)?d\s*\}?$/);if(!subst&&!del)throw Error('sed: se admiten sustitución s/patrón/texto/g, rango N,M y eliminación /patrón/d');for(let i=0;i<rows.length;i++){let line=rows[i];if(i+1>=start&&i+1<=end){if(subst){const r=regex(subst[2],extended);const re=new RegExp(r.source,subst[4].includes('g')?'g':'');line=line.replace(re,subst[3].replace(/&/g,'$&'));}else if(regex(del[1],extended).test(line)){if(writeDelete)captured.push(line);continue;}}result.push(line);}const out=result.join('\n')+(result.length?'\n':'');if(writeDelete)write(s,writeDelete[2].trim(),captured.join('\n')+(captured.length?'\n':''));if(inplace){if(files.length!==1)throw Error('sed -i: usa un archivo');write(s,files[0],out);return ok('','-i modifica el archivo. Sin -i, sed solo muestra la transformación.');}return ok(out,'sed transforma líneas. s sustituye coincidencias; g aplica todas por línea; d elimina una línea completa.');}
function awk(s,args,stdin){let fs=' ',script='',files=[];for(let i=0;i<args.length;i++){if(args[i]==='-F')fs=args[++i];else if(args[i].startsWith('-F'))fs=args[i].slice(2);else if(args[i]==='-f')script=read(s,args[++i]);else if(!script)script=args[i];else files.push(args[i]);}if(!script)throw Error('awk: falta un programa');let rs='\n',beginBlock='',endBlock='';const body=script.replace(/END\s*\{([^}]*)\}/g,(_,b)=>{endBlock=b;return '';}).replace(/BEGIN\s*\{([^}]*)\}/g,(_,b)=>{beginBlock=b;const f=b.match(/FS\s*=\s*"([^"\n]*)"/),r=b.match(/RS\s*=\s*"([^"\n]*)"/);if(f)fs=f[1].replace(/\\n/g,'\n');if(r)rs=r[1];return '';});const condition=body.match(/(?:if\s*\()?\s*\$([0-9]+)\s*(<|>|==|!=|<=|>=)\s*(\d+)\s*\)?/);const print=body.match(/print\s+([^}]+)/);if(!print)throw Error('awk: este entorno admite selección de campos con print y filtros numéricos');const raw=inputs(s,files,stdin);const records=rs===''?raw.trim().split(/\n\s*\n/):lines(raw);const block=b=>{const m=b.match(/print\s+(.+?)(?:;|$)/);if(!m)return [];const value=m[1].trim();if(value==='NR')return [String(records.length)];if(/^".*"$/.test(value))return [value.slice(1,-1).replace(/\\n/g,'\n').replace(/\\t/g,'\t')];throw Error('awk: BEGIN/END admiten print de texto entre comillas o NR');};const out=block(beginBlock);for(let i=0;i<records.length;i++){const record=records[i],fields=fs===' '?record.trim().split(/\s+/):record.split(fs);if(condition){const a=Number(fields[Number(condition[1])-1]),b=Number(condition[3]),op=condition[2];if(!({'<':a<b,'>':a>b,'==':a===b,'!=':a!==b,'<=':a<=b,'>=':a>=b}[op]))continue;}const items=print[1].trim().replace(/;$/,'').split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/);const value=e=>{e=e.trim();if(/^".*"$/.test(e))return e.slice(1,-1).replace(/\\t/g,'\t').replace(/\\n/g,'\n');if(e==='NR')return String(i+1);if(e==='NF')return String(fields.length);if(e==='$0')return record;if(e==='$NF')return fields.at(-1)??'';const m=e.match(/^\$\(NF\s*-\s*(\d+)\)$/);if(m)return fields[fields.length-1-Number(m[1])]??'';if(/^\$\d+$/.test(e))return fields[Number(e.slice(1))-1]??'';throw Error('awk: expresión no soportada '+e);};out.push(items.map(value).join(' '));}out.push(...block(endBlock));return ok(out.join('\n')+(out.length?'\n':''),'awk separa registros y campos. FS es el separador de campos; RS, el de registros; $1 es el primer campo, NF su cantidad y NR el número de registro.');}
export const COMMANDS=['pwd','cd','ls','mkdir','touch','cat','less','more','echo','printf','tee','head','tail','wc','grep','egrep','fgrep','cut','sort','uniq','chmod','umask','cp','mv','rm','rmdir','ln','find','sed','awk','id','whoami','who','ps','kill','uname','date','sleep','time','whereis','od','export','env','source','.','exec','alias','unalias','history','clear','exit','apt','apt-get','apt-cache','uptime','df','du','sudo','help','man'];
